
import React, { useState } from 'react';
import { ReturnItem } from '../types';
import { Download, Trash2, Edit2, Loader2 } from 'lucide-react';

interface ItemCardProps {
  item: ReturnItem;
  onDelete: (id: string) => void;
  onEdit: (item: ReturnItem) => void;
}

const ItemCard: React.FC<ItemCardProps> = ({ item, onDelete, onEdit }) => {
  const [isDeleting, setIsDeleting] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);

  const handleDownloadCard = async () => {
    setIsDownloading(true);
    try {
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d');
        if (!ctx) return;

        const img = new Image();
        img.crossOrigin = "anonymous"; // Useful for external images, handles CORS if server permits
        img.src = item.imageUrl;
        
        await new Promise((resolve, reject) => {
            img.onload = resolve;
            img.onerror = reject;
        });

        // Card Layout Configuration
        const cardWidth = 800; 
        const padding = 40;
        // Calculate image height maintaining aspect ratio
        const imgHeight = (cardWidth / img.width) * img.height;
        
        // Text settings
        const titleFont = 'bold 32px Inter, sans-serif';
        const dateFont = '18px Inter, sans-serif';
        const descFont = '22px Inter, sans-serif';
        const footerFont = 'italic 16px Inter, sans-serif';
        const lineHeight = 36;

        // Measure description height and wrap text
        ctx.font = descFont;
        const descWidth = cardWidth - (padding * 2);
        const words = item.description.split(' ');
        let line = '';
        let textHeight = 0;
        const lines: string[] = [];

        for(let n = 0; n < words.length; n++) {
            const testLine = line + words[n] + ' ';
            const metrics = ctx.measureText(testLine);
            if (metrics.width > descWidth && n > 0) {
                lines.push(line);
                line = words[n] + ' ';
                textHeight += lineHeight;
            } else {
                line = testLine;
            }
        }
        lines.push(line);
        textHeight += lineHeight;

        // Calculate total canvas height
        const headerHeight = 100; // Space for Title + Date
        const footerHeight = 80;  // Space for Branding
        const totalHeight = imgHeight + headerHeight + textHeight + footerHeight;

        // --- Draw Canvas ---
        canvas.width = cardWidth;
        canvas.height = totalHeight;

        // 1. Background (Dark Theme)
        const bgGradient = ctx.createLinearGradient(0, 0, 0, totalHeight);
        bgGradient.addColorStop(0, '#1F2937'); // Gray 800
        bgGradient.addColorStop(1, '#111827'); // Gray 900
        ctx.fillStyle = bgGradient;
        ctx.fillRect(0, 0, canvas.width, canvas.height);

        // 2. Draw Image
        ctx.drawImage(img, 0, 0, cardWidth, imgHeight);

        // 3. Image Bottom Border / Shadow
        ctx.shadowColor = "rgba(0,0,0,0.5)";
        ctx.shadowBlur = 20;
        ctx.strokeStyle = "rgba(255,255,255,0.1)";
        ctx.lineWidth = 1;
        ctx.beginPath();
        ctx.moveTo(0, imgHeight);
        ctx.lineTo(cardWidth, imgHeight);
        ctx.stroke();
        ctx.shadowBlur = 0; // Reset shadow

        let currentY = imgHeight + 50;

        // 4. Title
        ctx.fillStyle = '#F9FAFB'; // Gray 50
        ctx.font = titleFont;
        ctx.fillText(item.title, padding, currentY);
        
        // 5. Date
        currentY += 35;
        ctx.fillStyle = '#60A5FA'; // Blue 400
        ctx.font = dateFont;
        const dateStr = new Date(item.date).toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
        ctx.fillText(dateStr, padding, currentY);

        // 6. Description
        currentY += 50;
        ctx.fillStyle = '#D1D5DB'; // Gray 300
        ctx.font = descFont;
        lines.forEach(l => {
            ctx.fillText(l, padding, currentY);
            currentY += lineHeight;
        });

        // 7. Divider
        currentY += 20;
        ctx.strokeStyle = "rgba(255,255,255,0.1)";
        ctx.beginPath();
        ctx.moveTo(padding, currentY);
        ctx.lineTo(cardWidth - padding, currentY);
        ctx.stroke();

        // 8. Footer
        currentY += 40;
        ctx.fillStyle = '#6B7280'; // Gray 500
        ctx.font = footerFont;
        ctx.textAlign = 'center';
        ctx.fillText('Official Return Service Proof • Generated by ReturnServiceOS', cardWidth / 2, currentY);

        // --- Trigger Download ---
        const dataUrl = canvas.toDataURL('image/png');
        const link = document.createElement('a');
        link.download = `Proof-${item.title.replace(/[^a-z0-9]/gi, '_')}.png`;
        link.href = dataUrl;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);

    } catch (err) {
        console.error("Error generating card", err);
        alert("Failed to generate download card. Please try again.");
    } finally {
        setIsDownloading(false);
    }
  };

  return (
    <div className="glass-panel p-4 rounded-2xl flex flex-col sm:flex-row gap-6 transition-all hover:bg-white/5 group">
      {/* Image Thumb */}
      <div className="w-full sm:w-48 h-48 sm:h-32 flex-shrink-0 rounded-xl overflow-hidden border border-white/10 relative bg-black/40">
        <img 
          src={item.imageUrl} 
          alt={item.title} 
          className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
        />
      </div>

      {/* Content */}
      <div className="flex-1 flex flex-col justify-between">
        <div>
          <div className="flex justify-between items-start">
            <h4 className="text-lg font-bold text-white mb-1">{item.title}</h4>
            <span className="text-xs font-mono text-blue-300 bg-blue-900/30 px-2 py-1 rounded border border-blue-500/20">
              {new Date(item.date).toLocaleDateString()}
            </span>
          </div>
          <p className="text-gray-400 text-sm line-clamp-2 mb-4">{item.description}</p>
        </div>

        {/* Actions */}
        <div className="flex items-center gap-2 mt-4 sm:mt-0">
          <button 
            onClick={handleDownloadCard}
            disabled={isDownloading}
            className="p-2 rounded-lg hover:bg-white/10 text-gray-400 hover:text-blue-400 transition-colors disabled:opacity-50 flex items-center gap-2"
            title="Download Proof Card"
          >
            {isDownloading ? <Loader2 size={18} className="animate-spin" /> : <Download size={18} />}
            <span className="text-xs sm:hidden">Download Card</span>
          </button>
          <button 
            onClick={() => onEdit(item)}
            className="p-2 rounded-lg hover:bg-white/10 text-gray-400 hover:text-yellow-400 transition-colors"
            title="Edit"
          >
            <Edit2 size={18} />
          </button>
          
          {isDeleting ? (
             <div className="flex items-center gap-2 ml-auto animate-fade-in">
                <span className="text-xs text-red-400">Confirm?</span>
                <button onClick={() => onDelete(item.id)} className="text-xs font-bold text-red-500 hover:underline">Yes</button>
                <button onClick={() => setIsDeleting(false)} className="text-xs text-gray-400 hover:text-white">No</button>
             </div>
          ) : (
            <button 
                onClick={() => setIsDeleting(true)}
                className="p-2 rounded-lg hover:bg-red-500/20 text-gray-400 hover:text-red-400 transition-colors ml-auto"
                title="Delete"
            >
                <Trash2 size={18} />
            </button>
          )}
        </div>
      </div>
    </div>
  );
};

export default ItemCard;
